### ISSUE TITLE
There are some entity_name that causes error in expressionPlugin (.i.e. using ':')

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-node-lib#1223]
A device attribute defined like:

Protocol parameter | Device attribute | Type | Expression | Entity Type | Entity Name
temp2 | temperature2 | Number |   | thing2 | device:midisp1

is producing iotagent error:

time=2022-04-01T10:09:41.796Z | lvl=DEBUG | corr=e78bc118-e045-4f87-860f-8c3a256d8c1e | trans=e78bc118-e045-4f87-860f-8c3a256d8c1e | op=IoTAgentNGSI.expressionPlugin | from=n/a | srv=smartcity | subsrv=/ | msg=expressionPlugin entity {"temperature2":

{"type":"Number","value":31,"object_id":"temp2"},"id":"device:midisp1","type":"device"} | comp=IoTAgent
time=2022-04-01T10:24:21.724Z | lvl=ERROR | corr=91167125-2696-49f9-b2f3-4289fc16fa3a | trans=91167125-2696-49f9-b2f3-4289fc16fa3a | op=IoTAgentNGSI.expressionPlugin | from=n/a | srv=smartcity | subsrv=/ | msg=expressionPlugin error {"name":"INVALID_EXPRESSION","message":"Invalid expression in evaluation [device:midisp1]","code":400} entity {"temperature2":{"type":"Number","value":30,"object_id":"temp2"},"id":"device:midisp1","type":"device"} | comp=IoTAgent

time=2022-04-01T10:09:41.797Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | from=n/a | srv=n/a | subsrv=n/a | msg=An unexpected exception has been raised. Ignoring: Error: Callback was already called.
    at /opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:966:32
    at update (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/plugins/expressionPlugin.js:139:9)
    at nextTask (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5324:14)
    at next (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5331:9)
    at /opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:969:16
    at update (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/plugins/pluginUtils.js:134:9)
    at nextTask (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5324:14)
    at next (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5331:9)
    at /opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:969:16
    at updateAttribute (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/plugins/attributeAlias.js:98:5)
    at nextTask (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5324:14)
    at next (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5331:9)
    at /opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:969:16
    at emptyMiddleware (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/ngsi/ngsiUtils.js:193:9)
    at nextTask (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5334:5)
    at applyMiddlewares (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/ngsi/ngsiUtils.js:206:15)
    at /opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:66:19
    at nextTask (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5324:14)
    at next (/opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:5331:9)
    at /opt/iotagent-json/node_modules/iotagent-node-lib/node_modules/async/dist/async.js:969:16
    at add (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/stats/statsRegistry.js:60:5) | comp=IoTAgent

https://github.com/telefonicaid/iotagent-node-lib/blob/4741f7bc43ed5f2c3050d054e963ca7a59c07d6b/lib/plugins/expressionPlugin.js#L115-L124

**Comment by AlvaroVega** [comment]
Due to PR https://github.com/telefonicaid/iotagent-node-lib/pull/1254 this issue could be close since user client will obtain a proper response (invalid expression)
