### ISSUE TITLE
Issue using agentConsole.js: listdevices not working

### ISSUE THREAD

**Issue by javieriturra** [telefonicaid/iotagent-node-lib#69]
An error is raised running "listdevices" option from agent console:

IoTAgent> listdevices
/programs/telefonicaid/iotagent-node-lib/lib/services/deviceRegistryMemory.js:91
    callback(null, result);
    ^
TypeError: undefined is not a function
    at Object.listDevices [as list] (/programs/telefonicaid/iotagent-node-lib/lib/services/deviceRegistryMemory.js:91:5)
    at Object.listDevices (/programs/telefonicaid/iotagent-node-lib/lib/services/ngsiService.js:421:18)
    at Object.listDevices [as handler] (/programs/telefonicaid/iotagent-node-lib/bin/agentConsole.js:86:17)
    at executeCommander (/programs/telefonicaid/iotagent-node-lib/bin/agentConsole.js:175:30)
    at Interface.<anonymous> (/programs/telefonicaid/iotagent-node-lib/bin/agentConsole.js:216:9)
    at Interface.emit (events.js:107:17)
    at Interface._onLine (readline.js:214:10)
    at Interface._line (readline.js:553:8)
    at Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)

**Comment by dmoranj** [comment]
Fixed in #71
