### ISSUE TITLE
Issue using agentConsole.js: "updatevalue" not working.

### ISSUE THREAD

**Issue by javieriturra** [telefonicaid/iotagent-node-lib#70]
An error is raised when running "updatevalue" option from agent console:

IoTAgent> updatevalue l2 Light status/Boolean/false
time=2015-04-20T15:23:59.586Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAgentNGSI.NGSIService | msg=Updating device value in the Context Broker at [http://cbroot:1026/v1/updateContext]
time=2015-04-20T15:23:59.586Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAgentNGSI.NGSIService | msg=Using the following request:

{
    "url": "http://cbroot:1026/v1/updateContext",
    "method": "POST",
    "json": {
        "contextElements": [
            {
                "type": "Light",
                "isPattern": "false",
                "id": "l2"
            }
        ],
        "updateAction": "APPEND"
    },
    "headers": {
        "fiware-service": "wiseacess",
        "fiware-servicepath": "/garden",
        "X-Auth-Token": null
    }
}

time=2015-04-20T15:24:00.034Z | lvl=DEBUG | corr=n/a | trans=n/a | op=IoTAgentNGSI.NGSIService | msg=Value updated successfully
/programs/telefonicaid/iotagent-node-lib/lib/services/ngsiService.js:285
                callback(null, body);
                ^
TypeError: undefined is not a function
    at Request._callback (/programs/telefonicaid/iotagent-node-lib/lib/services/ngsiService.js:285:17)
    at Request.self.callback (/programs/telefonicaid/iotagent-node-lib/node_modules/request/request.js:123:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/programs/telefonicaid/iotagent-node-lib/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/programs/telefonicaid/iotagent-node-lib/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by dmoranj** [comment]
Fixed in #71
